import Appbar from "./components/Appbar";



export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Appbar/>
         
        {children}
        
      </body>
    </html>
  );
}
